import { SapphireClient } from "@sapphire/framework";
import { GuildMember, TextChannel } from "discord.js";
import { CustomEventEmitter, customPluginEvents } from ".";
import { colorToStyle, Colors } from "../constants/colors";
import { memberMention, codeBlock } from "../functions/formatting";
import { drawCard, Text } from "discord-welcome-card";

function welcomeJoinEvent() {
  CustomEventEmitter.on(customPluginEvents.WELCOME_PLUGIN_JOIN, async (client: SapphireClient, member: GuildMember) => {
    const data = client.LocalCacheStore.memory.plugins.welcome.get(member.guild);
    // const data = await WelcomePluginMongoModel.findOne({ guildID: member.guild.id });

    if (!data || data.Enabled === false || !data.GuildWelcomeTheme) return;

    if (data.GuildWelcomeChannelId) {
      const welcomeChannel = client.channels.cache.get(data.GuildWelcomeChannelId) as TextChannel;
      if (!welcomeChannel || !(welcomeChannel instanceof TextChannel)) return;
      switch (data.GuildWelcomeTheme) {
        case "text":
          await welcomeChannel
            .send({
              content: `${data
                .GuildWelcomeMessage!.replaceAll("{{user.mention}}", memberMention(member.id))
                .replaceAll("{{user.username}}", member.user.username)
                .replaceAll("{{user.id}}", member.id)
                .replaceAll("{{user.createdAt}}", member.user.createdAt.toLocaleDateString())
                .replaceAll("{{user.tag}}", member.user.tag)
                .replaceAll("{{server.memberCount}}", member.guild.memberCount.toString())
                .replaceAll("{{server.name}}", member.guild.name)
                .replaceAll("{{server.id}}", member.guild.id)}`,
            })
            .catch(() => { });
          break;
        case "card":
          if (
            !data.GuildWelcomeThemeUrl ||
            !data.GuildWelcomeThemeUrl.length ||
            !data.GuildWelcomeThemeUrl.includes("https://" || "http://")
          ) {
            await member
              .send({
                content: codeBlock(
                  "css",
                  `
=== Welcome Plugin Warning (Greeting) ===

[${member.user.username}] You are seeing this message because you have ran the simulate command. 
However, I noticed that you have an invalid custom image  url for your welcome card. 
If this is not set, the welcome card will not be generated at all.

[Your URl] = ${data.GuildWelcomeThemeUrl}

This message was automatically generated by the ${client.environment.bot.bot_full_name}
`
                ),
              })
              .catch(() => { });
          }
          return await drawCard({
            theme: "circuit",
            text: {
              title: new Text("Welcome!", 240, 70).setFontSize(32),
              text: new Text(member.user.tag, 240, 150).setFontSize(34),
              subtitle: `We now have {{server.memberCount}} members!`.replaceAll(
                "{{server.memberCount}}",
                member.guild.memberCount.toString()
              ),
              color: `#DDDDDD`,
              font: "Panton Black Caps",
            },
            avatar: {
              image: member.user.displayAvatarURL({ format: "png" }),
              outlineWidth: 5,
              outlineColor: colorToStyle(Colors.Amber),
              borderRadius: 1,
            },
            card: {
              background: data.GuildWelcomeThemeUrl,
              blur: 1,
              border: true,
              rounded: true,
            },
          }).then((image) => {
            welcomeChannel
              .send({
                content: data.GuildWelcomePingOnJoin ? `${memberMention(member.id)}` : null,
                files: [image],
              })
              .catch(() => { });
          });
        case "embed":
          // TODO: Add embed theme
          break;
        default:
          // If no theme is set, use the text theme
          await welcomeChannel
            .send({
              content: `${data
                .GuildWelcomeMessage!.replaceAll("{{user.mention}}", memberMention(member.id))
                .replaceAll("{{user.username}}", member.user.username)
                .replaceAll("{{user.createdAt}}", member.user.createdAt.toLocaleDateString())
                .replaceAll("{{user.id}}", member.id)
                .replaceAll("{{user.tag}}", member.user.tag)
                .replaceAll("{{server.id}}", member.guild.id)}`,
            })
            .catch(() => { });
          break;
      }
    } else {
      client.logger.warn(`[WELCOME] No welcome channel found for ${member.guild.name}`);
    }
  });
}

function welcomeLeaveEvent() {
  CustomEventEmitter.on(customPluginEvents.WELCOME_PLUGIN_LEAVE, async (client: SapphireClient, member: GuildMember) => {
    const data = client.LocalCacheStore.memory.plugins.welcome.get(member.guild);
    // const data = await WelcomePluginMongoModel.findOne({ guildID: member.guild.id });

    if (!data || data.Enabled === false || !data.GuildWelcomeTheme) return;

    if (data.GuildGoodbyeChannelId) {
      const goodbyeChannel = client.channels.cache.get(data.GuildGoodbyeChannelId) as TextChannel;
      // checks if goodbye channel type is TextChannel
      if (!goodbyeChannel || !(goodbyeChannel instanceof TextChannel)) return;
      switch (data.GuildWelcomeTheme) {
        case "text":
          await goodbyeChannel.send({
            content: `${data
              .GuildGoodbyeMessage!.replaceAll("{{user.mention}}", memberMention(member.id))
              .replaceAll("{{user.username}}", member.user.username)
              .replaceAll("{{user.id}}", member.id)
              .replaceAll("{{user.tag}}", member.user.tag)
              .replaceAll("{{server.memberCount}}", member.guild.memberCount.toString())
              .replaceAll("{{server.name}}", member.guild.name)
              .replaceAll("{{server.id}}", member.guild.id)}`.replaceAll(
                "{{user.createdAt}}",
                member.user.createdAt.toLocaleDateString()
              ),
          });
          break;
        case "card":
          if (
            !data.GuildWelcomeThemeUrl ||
            !data.GuildWelcomeThemeUrl.length ||
            !data.GuildWelcomeThemeUrl.includes("https://" || "http://")
          ) {
            await member
              .send({
                content: codeBlock(
                  "css",
                  `
            === Welcome Plugin Warning (Goodbye) ===

            [${member.user.username}] You are seeing this message because you have ran the simulate command.
            However, I noticed that you have an invalid custom image  url for your welcome card.
            If this is not set, the welcome card will not be generated at all.

            [Your URl] = ${data.GuildWelcomeThemeUrl}

            This message was automatically generated by the ${client.environment.bot.bot_full_name}
            `
                ),
              })
              .catch(() => { });
          }

          await drawCard({
            theme: "circuit",
            text: {
              title: new Text("Goodbye!", 240, 70).setFontSize(32),
              text: new Text(member.user.tag, 240, 150).setFontSize(34),
              subtitle: `We now have {{server.memberCount}} members!`.replaceAll(
                "{{server.memberCount}}",
                member.guild.memberCount.toString()
              ),
              color: `#DDDDDD`,
              font: "Panton Black Caps",
            },
            avatar: {
              image: member.user.displayAvatarURL({ format: "png" }),
              outlineWidth: 5,
              outlineColor: colorToStyle(Colors.Amber),
              borderRadius: 1,
            },
            card: {
              background: data.GuildWelcomeThemeUrl,
              blur: 1,
              border: true,
              rounded: true,
            },
          }).then((image) => {
            goodbyeChannel
              .send({
                content: data.GuildWelcomePingOnJoin ? `${memberMention(member.id)}` : null,
                files: [image],
              })
              .catch(() => { });
          });
          break;
        case "embed":
          // TODO: Add embed theme
          break;
        default:
          // If no theme is set, use the text theme
          await goodbyeChannel.send({
            content: `${data
              .GuildWelcomeMessage!.replaceAll("{{user.mention}}", memberMention(member.id))
              .replaceAll("{{user.username}}", member.user.username)
              .replaceAll("{{user.id}}", member.id)
              .replaceAll("{{user.tag}}", member.user.tag)
              .replaceAll("{{server.id}}", member.guild.id)}`.replaceAll(
                "{{user.createdAt}}",
                member.user.createdAt.toLocaleDateString()
              ),
          });
          break;
      }
    } else {
      client.logger.warn(`[GOODBYE] No goodbye channel found for ${member.guild.name}`);
    }
  });

}

export { welcomeJoinEvent, welcomeLeaveEvent }